apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  namespace: cert-manager
  name: tap-gui
spec:
  commonName: tap-gui.$ING_HOST
  dnsNames:
    - tap-gui.$ING_HOST
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  secretName: tap-gui