apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  namespace: $NS
  name: tanzu-app-deploy
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-app
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  source:
    git:
      url: https://github.com/ezYakaEagle442/tanzu-simple
      ref:
        branch: main
