# https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.4/tap/install.html#full-profile
profile: full

shared:
  ingress_domain: $APP_DNS_ZONE
  ingress_issuer: letsencrypt-production # https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.4/tap/security-and-compliance-ingress-certificates.html
  image_registry:
    project_path: "$REGISTRY_URL/$REPOSITORY/supply-chain"
    username: $REPOSITORY_USERNAME # TODO: ask RFE  NOT to use it
    password: $REPOSITORY_PASSWORD

appliveview:
  ingressEnabled: "true"
appliveview_connector:
  backend:
    sslDisabled: "true"

# Installation fails if this is not set to true
# Tanzu Application Platform is part of VMware’s CEIP program where data is collected to help improve the customer experience.
#  By setting ceip_policy_disclosed to true (not a string), you acknowledge the program is disclosed to you and you are aware
# data collection is happening. This field must be set for the installation to be completed.
ceip_policy_disclosed: true

excluded_packages:
  - learningcenter.tanzu.vmware.com
  - workshops.learningcenter.tanzu.vmware.com
  - policy.apps.tanzu.vmware.com
  - image-policy-webhook.signing.apps.tanzu.vmware.com  

buildservice:
  kp_default_repository: $REGISTRY_URL/$REPOSITORY/build-service/
  kp_default_repository_username: $REPOSITORY_USERNAME # TODO: ask RFE  NOT to use it
  kp_default_repository_password: $REPOSITORY_PASSWORD
  tanzunet_username: $TANZU_NET_USER
  tanzunet_password: $TANZU_NET_PASSWORD
  exclude_dependencies: true # https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.4/tap/install.html#tap-install-full-deps
  #   enable_automatic_dependency_updates: false

supply_chain: basic

# OOTB : Out Of The Box
ootb_supply_chain_basic:
  registry:
    server: $REGISTRY_URL
    repository: $REPOSITORY/$REPO_SUBFOLDER_APP_TAP
  gitops:
    # Leave empty for public repos, add a secret for private repos.
    ssh_secret: ""

# https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.4/tap/tap-gui-accessing-tap-gui.html
tap_gui:
  tls: # https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.4/tap/tap-gui-tls-cert-mngr-ext-clusterissuer.html
   namespace: cert-manager
   secretName: tap-gui
  service_type: ClusterIP # default to LoadBalancer , other option: ClusterIP
  app_config:
    app:
      baseUrl: https://tap-gui.$APP_DNS_ZONE # https if TLS is enabled
    integrations:
      github: 
        - host: github.com
          token: $GH_PAT # For GitOps or Accelerators
    proxy:
      /metadata-store:
        target: https://metadata-store-app.metadata-store:8443/api/v1
        changeOrigin: true
        secure: false
        headers:
          Authorization: "Bearer $METADATA_STORE_ACCESS_TOKEN" # TODO: need to get a Bearer TOKEN AFTER the TAP installation ...
          X-Custom-Source: project-star
    catalog:
      locations:
        - type: url
          # Catalog repository
          target: $CATALOG_URL/blob/main/catalog-info.yaml
    backend:
        baseUrl: http://tap-gui.$APP_DNS_ZONE
        cors:
            origin: http://tap-gui.$APP_DNS_ZONE
        # https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.4/tap/tap-gui-database.html
        #database:
        #client: pg
        #connection:
        #  host: $PG_SQL_HOSTNAME
        #  port: 5432
        #  user: $PG_SQL_USERNAME
        #  password: $PG_SQL_PASSWORD
        #  ssl: {rejectUnauthorized: false} # Set to true if using SSL

grype:
  namespace: "$DEV_NAMESPACE"
  targetImagePullSecret: "acr-registry-credentials" # TARGET-REGISTRY-CREDENTIALS-SECRET is the name of the secret that contains the credentials to pull an image from the registry for scanning

policy:
  tuf_enabled: false # By default, TUF initialization and keyless verification are deactivated.

#tap_telemetry:
#  customer_entitlement_account_number: "CUSTOMER-ENTITLEMENT-ACCOUNT-NUMBER" # (Optional) Identify data for creating Tanzu Application Platform usage reports.

contour:
  infrastructure_provider: azure
  envoy:
    service:
      type: LoadBalancer
      #annotations: 
        #service.beta.kubernetes.io/azure-dns-label-name: $AZURE_DNS_LABEL_NAME # RFE: need to add Azure annotations in the docs

# Cloud Native Runtime Services
cnrs:
  provider: local
  domain_name: "$APP_DNS_ZONE"
  # Fix domain template for TSL certficates
  domain_template: "{{.Name}}-{{.Namespace}}.{{.Domain}}"

metadata_store:
  ns_for_export_app_cert: "$DEV_NAMESPACE"
  app_service_type: ClusterIP

scanning:
  metadataStore:
    url: "" # Disable embedded integration since it's deprecated

api_portal:
  apiPortalServer:
    sourceUrls: "https://petstore.swagger.io/v2/swagger.json,https://petstore3.swagger.io/api/v3/openapi.json"